application:
  moduleName: module1
  serviceName: config-profiling
  packedScanner: default

monitoring:
  logLevel: INFO
  monitoringArgumentMethod: false
  monitoringReturnMethod: false
  monitoringStaticMethod: false
  monitoringOnlySpringComponent: true
  sendMonitoringFiles:
    serverConsumer:
      url: http://localhost:8080
    schedulerTimer: 10000

authorisation:
  token: 34geg54gb4

